"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Team(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    id: builtins.int = ...
    name: typing.Text = ...

    def __init__(self,
        *,
        id : builtins.int = ...,
        name : typing.Text = ...,
        ) -> None: ...

    def ClearField(self, field_name: str) -> None: ...
global___Team = Team
