workspace(name = "bazel_mypy_integration_issue_36")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

rules_python_version = "0.1.0"

http_archive(
    name = "rules_python",
    sha256 = "b6d46438523a3ec0f3cead544190ee13223a52f6a6765a29eae7b7cc24cc83a0",
    urls = [
        "http://github-cache.canva-build.com/bazelbuild/rules_python/releases/download/{version}/rules_python-{version}.tar.gz".format(version = rules_python_version),
        "https://github.com/bazelbuild/rules_python/releases/download/{version}/rules_python-{version}.tar.gz".format(version = rules_python_version),
    ],
)

load("@rules_python//python:pip.bzl", "pip_install")

pip_install(
    name = "deps",
    requirements = "@//:requirements.txt",
)

# MyPy Support
mypy_integration_version = "0.1.0"

http_archive(
    name = "mypy_integration",
    sha256 = "14d63ffa2a95e42ae468ad8785eec6c2cc489ce3b382cd0bdc7a4d115cf601b4",
    urls = [
        "http://github-cache.canva-build.com/thundergolfer/bazel-mypy-integration/releases/download/{version}/bazel_mypy_integration-{version}.tar.gz".format(version = mypy_integration_version),
        "https://github.com/thundergolfer/bazel-mypy-integration/releases/download/{version}/bazel_mypy_integration-{version}.tar.gz".format(version = mypy_integration_version),
    ],
)

load(
    "@mypy_integration//repositories:repositories.bzl",
    mypy_integration_repositories = "repositories",
)

mypy_integration_repositories()

load("@mypy_integration//:config.bzl", "mypy_configuration")

mypy_configuration("//tools/build/python/typing:mypy.ini")

load("@mypy_integration//repositories:deps.bzl", mypy_integration_deps = "deps")

mypy_integration_deps("//tools/build/python/typing:mypy_version.txt")

register_toolchains("//:python_toolchain")
